print ( 'Contest-type:text/html\r\n\r\n' )
print( '<!DOCTYPE HTML>' )
print( '<html lang="en">' )
print( '<head>' )
print( '<meta charset="UTF-8">' )
print( '<title>Python Response</title>' )
print( '<head>' )
print( '<body>' )
print( '<h1>Hello!</h1>' )
print( '</html>')